project:
  type: book

book:
  title: "IDR4000 Mappeeksamen"
  author: "Kandidatnr."
  date: "17.11.2023"
  chapters:
    - index.qmd
    - 01-reliabilitet.qmd
    - 02-vitenskapsfilosofi.qmd 
    - 03-proteinanalyse.qmd 
    - 04-studiedesign.qmd 
    - 05-repeterte-forsøk.qmd
    - references.qmd 
    
output:
  pdf_document:
    citation_package: natbib
    citation_style: referansestil/apa.csl 
editor_options: 
  chunk_output_type: console 

bibliography: resources/referanser.bib 

header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Times New Roman} 
  - \renewcommand{\normalsize}{\fontsize{12}{18}\selectfont}

crossref: 
  fig-title: "**Figur**" 
  fig-prefix: "Figur"
  tbl-title: "**Tabell**" 
  tbl-prefix: "Tabell"
  
  
execute: 
  echo: false 
  warning: false 
  message: false 

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt 
    toc-title: "Innholdsfortegnelse" 
    



