project:
  type: book

book:
  title: "IDR4000 Mappeeksamen"
  author: "Kandidat NR"
  date: "17/11/2023"
  chapters:
    - index.qmd
    - 01-reliabilitet.qmd
    - 02-vitenskapsfilosofi.qmd
    - references.qmd

bibliography: resources/references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt



