project: 
  type: book

book:
  title: "IDR4000 Mappeeksamen"
  author: "Kandidatnr. 413"
  date: "2023-11-17" 
  chapters:
    - index.qmd
    - 01-reliabilitet.qmd 
    - 02-proteinanalyse.qmd 
    - 03-vitenskapsfilosofi.qmd 
    - 04-studiedesign.qmd 
    - 05-repeterte-forsøk.qmd
    - references.qmd 
    
bibliography: resources/referanser.bib 

output:
  pdf_document: 
    citation_style: referansestil/apa.csl 
    citation_package: natbib 
    latex_engine: xelatex 
    includes:
      in_header: "lenke-git.tex" 

editor_options: 
  chunk_output_type: console 

header-includes:
  - \usepackage{fontspec}
  - \setmainfont{Times New Roman} 
  - \renewcommand{\normalsize}{\fontsize{12}{18}\selectfont}

crossref: 
  fig-title: "**Figur**" 
  fig-prefix: "Figur"
  tbl-title: "**Tabell**" 
  tbl-prefix: "Tabell"
  
  
execute: 
  echo: false 
  warning: false 
  message: false 

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt 
    toc-title: "Innholdsfortegnelse" 
    



